import { IChannel } from '@/types/channel.types';

export const mockChannels: IChannel[] = [
  { id: 1, name: 'General' },
  { id: 2, name: 'Random' },
  { id: 3, name: 'Tech Talk' },
  { id: 4, name: 'Gaming' },
  { id: 5, name: 'Music' },
  { id: 6, name: 'Movies' },
  { id: 7, name: 'Programming' },
  { id: 8, name: 'Startups' },
  { id: 9, name: 'AI Discussions' },
  { id: 10, name: 'Fitness' },
  { id: 11, name: 'Foodies' },
  { id: 12, name: 'Travel' },
  { id: 13, name: 'Photography' },
  { id: 14, name: 'Design' },
  { id: 15, name: 'Art' },
  { id: 16, name: 'Memes' },
  { id: 17, name: 'Books' },
  { id: 18, name: 'Finance' },
  { id: 19, name: 'Crypto' },
  { id: 20, name: 'Investing' },
  { id: 21, name: 'Marketing' },
  { id: 22, name: 'Business' },
  { id: 23, name: 'Entrepreneurship' },
  { id: 24, name: 'Self Improvement' },
  { id: 25, name: 'Career' },
  { id: 26, name: 'Language Learning' },
  { id: 27, name: 'Science' },
  { id: 28, name: 'Space' },
  { id: 29, name: 'Astronomy' },
  { id: 30, name: 'Mathematics' },
  { id: 31, name: 'Physics' },
  { id: 32, name: 'Chemistry' },
  { id: 33, name: 'Biology' },
  { id: 34, name: 'Technology' },
  { id: 35, name: 'Engineering' },
  { id: 36, name: 'Robotics' },
  { id: 37, name: 'Virtual Reality' },
  { id: 38, name: 'Augmented Reality' },
  { id: 39, name: 'Cybersecurity' },
  { id: 40, name: 'DevOps' },
];
